// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.1
// source: api/setting/setting.proto

package setting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingRequest) Reset() {
	*x = GetSettingRequest{}
	mi := &file_api_setting_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingRequest) ProtoMessage() {}

func (x *GetSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingRequest.ProtoReflect.Descriptor instead.
func (*GetSettingRequest) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{0}
}

type GetSettingResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SchoolName          string                 `protobuf:"bytes,1,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`                               // 学校名称 / 学校名
	PrincipalName       string                 `protobuf:"bytes,2,opt,name=principal_name,json=principalName,proto3" json:"principal_name,omitempty"`                      // 校长姓名 / 校長名
	EmailDomain         string                 `protobuf:"bytes,3,opt,name=email_domain,json=emailDomain,proto3" json:"email_domain,omitempty"`                            // 邮箱后缀 / メールドメイン（例：@school.jp）
	AllowRegister       bool                   `protobuf:"varint,4,opt,name=allow_register,json=allowRegister,proto3" json:"allow_register,omitempty"`                     // 是否允许注册 / 登録許可
	AllowChangeDevice   bool                   `protobuf:"varint,5,opt,name=allow_change_device,json=allowChangeDevice,proto3" json:"allow_change_device,omitempty"`       // 是否允许更换登录设备 / デバイス変更許可
	RestrictClockInIp   bool                   `protobuf:"varint,6,opt,name=restrict_clock_in_ip,json=restrictClockInIp,proto3" json:"restrict_clock_in_ip,omitempty"`     // 是否限制打卡IP / 打刻IP制限
	RestrictIpList      string                 `protobuf:"bytes,7,opt,name=restrict_ip_list,json=restrictIpList,proto3" json:"restrict_ip_list,omitempty"`                 // 限制打卡IP列表（逗号分隔）/ 打刻許可IPリスト（カンマ区切り）
	RestrictEmailDomain bool                   `protobuf:"varint,8,opt,name=restrict_email_domain,json=restrictEmailDomain,proto3" json:"restrict_email_domain,omitempty"` // 是否开启邮箱后缀注册限制 / メールドメイン制限登録を有効にする
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSettingResponse) Reset() {
	*x = GetSettingResponse{}
	mi := &file_api_setting_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingResponse) ProtoMessage() {}

func (x *GetSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_setting_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingResponse.ProtoReflect.Descriptor instead.
func (*GetSettingResponse) Descriptor() ([]byte, []int) {
	return file_api_setting_setting_proto_rawDescGZIP(), []int{1}
}

func (x *GetSettingResponse) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *GetSettingResponse) GetPrincipalName() string {
	if x != nil {
		return x.PrincipalName
	}
	return ""
}

func (x *GetSettingResponse) GetEmailDomain() string {
	if x != nil {
		return x.EmailDomain
	}
	return ""
}

func (x *GetSettingResponse) GetAllowRegister() bool {
	if x != nil {
		return x.AllowRegister
	}
	return false
}

func (x *GetSettingResponse) GetAllowChangeDevice() bool {
	if x != nil {
		return x.AllowChangeDevice
	}
	return false
}

func (x *GetSettingResponse) GetRestrictClockInIp() bool {
	if x != nil {
		return x.RestrictClockInIp
	}
	return false
}

func (x *GetSettingResponse) GetRestrictIpList() string {
	if x != nil {
		return x.RestrictIpList
	}
	return ""
}

func (x *GetSettingResponse) GetRestrictEmailDomain() bool {
	if x != nil {
		return x.RestrictEmailDomain
	}
	return false
}

var File_api_setting_setting_proto protoreflect.FileDescriptor

const file_api_setting_setting_proto_rawDesc = "" +
	"\n" +
	"\x19api/setting/setting.proto\x12\asetting\"\x13\n" +
	"\x11GetSettingRequest\"\xe5\x02\n" +
	"\x12GetSettingResponse\x12\x1f\n" +
	"\vschool_name\x18\x01 \x01(\tR\n" +
	"schoolName\x12%\n" +
	"\x0eprincipal_name\x18\x02 \x01(\tR\rprincipalName\x12!\n" +
	"\femail_domain\x18\x03 \x01(\tR\vemailDomain\x12%\n" +
	"\x0eallow_register\x18\x04 \x01(\bR\rallowRegister\x12.\n" +
	"\x13allow_change_device\x18\x05 \x01(\bR\x11allowChangeDevice\x12/\n" +
	"\x14restrict_clock_in_ip\x18\x06 \x01(\bR\x11restrictClockInIp\x12(\n" +
	"\x10restrict_ip_list\x18\a \x01(\tR\x0erestrictIpList\x122\n" +
	"\x15restrict_email_domain\x18\b \x01(\bR\x13restrictEmailDomain2W\n" +
	"\x0eSettingService\x12E\n" +
	"\n" +
	"GetSetting\x12\x1a.setting.GetSettingRequest\x1a\x1b.setting.GetSettingResponseB\x15Z\x13api/setting;settingb\x06proto3"

var (
	file_api_setting_setting_proto_rawDescOnce sync.Once
	file_api_setting_setting_proto_rawDescData []byte
)

func file_api_setting_setting_proto_rawDescGZIP() []byte {
	file_api_setting_setting_proto_rawDescOnce.Do(func() {
		file_api_setting_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_setting_setting_proto_rawDesc), len(file_api_setting_setting_proto_rawDesc)))
	})
	return file_api_setting_setting_proto_rawDescData
}

var file_api_setting_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_setting_setting_proto_goTypes = []any{
	(*GetSettingRequest)(nil),  // 0: setting.GetSettingRequest
	(*GetSettingResponse)(nil), // 1: setting.GetSettingResponse
}
var file_api_setting_setting_proto_depIdxs = []int32{
	0, // 0: setting.SettingService.GetSetting:input_type -> setting.GetSettingRequest
	1, // 1: setting.SettingService.GetSetting:output_type -> setting.GetSettingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_setting_setting_proto_init() }
func file_api_setting_setting_proto_init() {
	if File_api_setting_setting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_setting_setting_proto_rawDesc), len(file_api_setting_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_setting_setting_proto_goTypes,
		DependencyIndexes: file_api_setting_setting_proto_depIdxs,
		MessageInfos:      file_api_setting_setting_proto_msgTypes,
	}.Build()
	File_api_setting_setting_proto = out.File
	file_api_setting_setting_proto_goTypes = nil
	file_api_setting_setting_proto_depIdxs = nil
}
