// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.1
// source: api/student/student.proto

package student

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckInRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                            // 打卡类型（entry=入校、exit=退校、class=上课签到）/ 打刻タイプ（entry＝登校、exit＝下校、class＝授業出席）
	CourseId            string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`                                    // 课程ID（只有上课打卡时填写，入校/退校为空）/ 講義ID（授業打刻の場合のみ）
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                        // 出勤状态（present=出席、absent=缺席、late=迟到）/ 出席状況（present＝出席、absent＝欠席、late＝遅刻）
	Timestamp           int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                 // 打卡时间（Unix时间戳）/ 打刻時間（Unixタイムスタンプ）
	DeviceId            string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                    // 打卡设备编号 / 打刻端末ID
	Location            string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`                                                    // 打卡地点描述（例：北门、教学楼A）/ 打刻場所（例：北門、講義棟A）
	BluetoothTerminalId string                 `protobuf:"bytes,7,opt,name=bluetooth_terminal_id,json=bluetoothTerminalId,proto3" json:"bluetooth_terminal_id,omitempty"` // 蓝牙终端ID（例如用于室内定位辅助打卡）/ Bluetooth端末ID（屋内位置情報支援のため）
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_api_student_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{0}
}

func (x *CheckInRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CheckInRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CheckInRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckInRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CheckInRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CheckInRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CheckInRequest) GetBluetoothTerminalId() string {
	if x != nil {
		return x.BluetoothTerminalId
	}
	return ""
}

type CheckInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	mi := &file_api_student_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{1}
}

type CheckInRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 打卡时间（Unix时间戳）/ 打刻時間（Unixタイムスタンプ）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRecordsRequest) Reset() {
	*x = CheckInRecordsRequest{}
	mi := &file_api_student_student_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRecordsRequest) ProtoMessage() {}

func (x *CheckInRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRecordsRequest.ProtoReflect.Descriptor instead.
func (*CheckInRecordsRequest) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{2}
}

func (x *CheckInRecordsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CheckInRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*CheckInRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRecordsResponse) Reset() {
	*x = CheckInRecordsResponse{}
	mi := &file_api_student_student_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRecordsResponse) ProtoMessage() {}

func (x *CheckInRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRecordsResponse.ProtoReflect.Descriptor instead.
func (*CheckInRecordsResponse) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{3}
}

func (x *CheckInRecordsResponse) GetRecords() []*CheckInRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type CheckInRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// 打卡类型（entry=入校、exit=退校、class=上课签到）/ 打刻タイプ（entry＝登校、exit＝下校、class＝授業出席）
	CourseId string `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	// 课程ID（只有上课打卡时填写，入校/退校为空）/ 講義ID（授業打刻の場合のみ）
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// 出勤状态（present=出席、absent=缺席、late=迟到）/ 出席状況（present＝出席、absent＝欠席、late＝遅刻）
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 打卡时间（Unix时间戳）/ 打刻時間（Unixタイムスタンプ）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRecord) Reset() {
	*x = CheckInRecord{}
	mi := &file_api_student_student_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRecord) ProtoMessage() {}

func (x *CheckInRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRecord.ProtoReflect.Descriptor instead.
func (*CheckInRecord) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{4}
}

func (x *CheckInRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CheckInRecord) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CheckInRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckInRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CheckInCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInCoursesRequest) Reset() {
	*x = CheckInCoursesRequest{}
	mi := &file_api_student_student_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInCoursesRequest) ProtoMessage() {}

func (x *CheckInCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInCoursesRequest.ProtoReflect.Descriptor instead.
func (*CheckInCoursesRequest) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{5}
}

type CheckInCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*CheckInCourse       `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInCoursesResponse) Reset() {
	*x = CheckInCoursesResponse{}
	mi := &file_api_student_student_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInCoursesResponse) ProtoMessage() {}

func (x *CheckInCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInCoursesResponse.ProtoReflect.Descriptor instead.
func (*CheckInCoursesResponse) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{6}
}

func (x *CheckInCoursesResponse) GetCourses() []*CheckInCourse {
	if x != nil {
		return x.Courses
	}
	return nil
}

type CheckInCourse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DayOfWeek     string                 `protobuf:"bytes,6,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInCourse) Reset() {
	*x = CheckInCourse{}
	mi := &file_api_student_student_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInCourse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInCourse) ProtoMessage() {}

func (x *CheckInCourse) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInCourse.ProtoReflect.Descriptor instead.
func (*CheckInCourse) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{7}
}

func (x *CheckInCourse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckInCourse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckInCourse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CheckInCourse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CheckInCourse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CheckInCourse) GetDayOfWeek() string {
	if x != nil {
		return x.DayOfWeek
	}
	return ""
}

type UpdateUserAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAvatarRequest) Reset() {
	*x = UpdateUserAvatarRequest{}
	mi := &file_api_student_student_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAvatarRequest) ProtoMessage() {}

func (x *UpdateUserAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAvatarRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAvatarRequest) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserAvatarRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateUserAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserAvatarResponse) Reset() {
	*x = UpdateUserAvatarResponse{}
	mi := &file_api_student_student_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAvatarResponse) ProtoMessage() {}

func (x *UpdateUserAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_student_student_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAvatarResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserAvatarResponse) Descriptor() ([]byte, []int) {
	return file_api_student_student_proto_rawDescGZIP(), []int{9}
}

var File_api_student_student_proto protoreflect.FileDescriptor

const file_api_student_student_proto_rawDesc = "" +
	"\n" +
	"\x19api/student/student.proto\x12\astudent\"\xe4\x01\n" +
	"\x0eCheckInRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x122\n" +
	"\x15bluetooth_terminal_id\x18\a \x01(\tR\x13bluetoothTerminalId\"\x11\n" +
	"\x0fCheckInResponse\"5\n" +
	"\x15CheckInRecordsRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"J\n" +
	"\x16CheckInRecordsResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.student.CheckInRecordR\arecords\"v\n" +
	"\rCheckInRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x17\n" +
	"\x15CheckInCoursesRequest\"J\n" +
	"\x16CheckInCoursesResponse\x120\n" +
	"\acourses\x18\x01 \x03(\v2\x16.student.CheckInCourseR\acourses\"\xa9\x01\n" +
	"\rCheckInCourse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x1e\n" +
	"\vday_of_week\x18\x06 \x01(\tR\tdayOfWeek\"1\n" +
	"\x17UpdateUserAvatarRequest\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\"\x1a\n" +
	"\x18UpdateUserAvatarResponse2\xcd\x02\n" +
	"\x0eStudentService\x12W\n" +
	"\x10UpdateUserAvatar\x12 .student.UpdateUserAvatarRequest\x1a!.student.UpdateUserAvatarResponse\x12<\n" +
	"\aCheckIn\x12\x17.student.CheckInRequest\x1a\x18.student.CheckInResponse\x12Q\n" +
	"\x0eCheckInCourses\x12\x1e.student.CheckInCoursesRequest\x1a\x1f.student.CheckInCoursesResponse\x12Q\n" +
	"\x0eCheckInRecords\x12\x1e.student.CheckInRecordsRequest\x1a\x1f.student.CheckInRecordsResponseB\x15Z\x13api/student;studentb\x06proto3"

var (
	file_api_student_student_proto_rawDescOnce sync.Once
	file_api_student_student_proto_rawDescData []byte
)

func file_api_student_student_proto_rawDescGZIP() []byte {
	file_api_student_student_proto_rawDescOnce.Do(func() {
		file_api_student_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_student_student_proto_rawDesc), len(file_api_student_student_proto_rawDesc)))
	})
	return file_api_student_student_proto_rawDescData
}

var file_api_student_student_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_student_student_proto_goTypes = []any{
	(*CheckInRequest)(nil),           // 0: student.CheckInRequest
	(*CheckInResponse)(nil),          // 1: student.CheckInResponse
	(*CheckInRecordsRequest)(nil),    // 2: student.CheckInRecordsRequest
	(*CheckInRecordsResponse)(nil),   // 3: student.CheckInRecordsResponse
	(*CheckInRecord)(nil),            // 4: student.CheckInRecord
	(*CheckInCoursesRequest)(nil),    // 5: student.CheckInCoursesRequest
	(*CheckInCoursesResponse)(nil),   // 6: student.CheckInCoursesResponse
	(*CheckInCourse)(nil),            // 7: student.CheckInCourse
	(*UpdateUserAvatarRequest)(nil),  // 8: student.UpdateUserAvatarRequest
	(*UpdateUserAvatarResponse)(nil), // 9: student.UpdateUserAvatarResponse
}
var file_api_student_student_proto_depIdxs = []int32{
	4, // 0: student.CheckInRecordsResponse.records:type_name -> student.CheckInRecord
	7, // 1: student.CheckInCoursesResponse.courses:type_name -> student.CheckInCourse
	8, // 2: student.StudentService.UpdateUserAvatar:input_type -> student.UpdateUserAvatarRequest
	0, // 3: student.StudentService.CheckIn:input_type -> student.CheckInRequest
	5, // 4: student.StudentService.CheckInCourses:input_type -> student.CheckInCoursesRequest
	2, // 5: student.StudentService.CheckInRecords:input_type -> student.CheckInRecordsRequest
	9, // 6: student.StudentService.UpdateUserAvatar:output_type -> student.UpdateUserAvatarResponse
	1, // 7: student.StudentService.CheckIn:output_type -> student.CheckInResponse
	6, // 8: student.StudentService.CheckInCourses:output_type -> student.CheckInCoursesResponse
	3, // 9: student.StudentService.CheckInRecords:output_type -> student.CheckInRecordsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_student_student_proto_init() }
func file_api_student_student_proto_init() {
	if File_api_student_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_student_student_proto_rawDesc), len(file_api_student_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_student_student_proto_goTypes,
		DependencyIndexes: file_api_student_student_proto_depIdxs,
		MessageInfos:      file_api_student_student_proto_msgTypes,
	}.Build()
	File_api_student_student_proto = out.File
	file_api_student_student_proto_goTypes = nil
	file_api_student_student_proto_depIdxs = nil
}
